// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX2hfXW66gAC9sB_A9_C6WoV99LwUTWAg',
    appId: '1:223710503102:web:b5175c0b494e0b18067eef',
    messagingSenderId: '223710503102',
    projectId: 'let-stalk-87b18',
    authDomain: 'let-stalk-87b18.firebaseapp.com',
    storageBucket: 'let-stalk-87b18.firebasestorage.app',
    measurementId: 'G-0LN5NPL6H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB83u4RKdeyhwQ6KhWzneQhTWrVoJ7C1U',
    appId: '1:223710503102:android:c68c9fb6acfd3ec6067eef',
    messagingSenderId: '223710503102',
    projectId: 'let-stalk-87b18',
    storageBucket: 'let-stalk-87b18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALwHhmq10kMo2niKd8n5hUYnCY29BPZnU',
    appId: '1:223710503102:ios:45ab15509aa691d9067eef',
    messagingSenderId: '223710503102',
    projectId: 'let-stalk-87b18',
    storageBucket: 'let-stalk-87b18.firebasestorage.app',
    iosBundleId: 'com.example.letsTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBX2hfXW66gAC9sB_A9_C6WoV99LwUTWAg',
    appId: '1:223710503102:web:c6095eb75b44485f067eef',
    messagingSenderId: '223710503102',
    projectId: 'let-stalk-87b18',
    authDomain: 'let-stalk-87b18.firebaseapp.com',
    storageBucket: 'let-stalk-87b18.firebasestorage.app',
    measurementId: 'G-P5CCYCDESX',
  );
}
